In [ ]:
import numpy as np

x = np.arange(15,dtype = np.int64)
x = x.reshape(3,5) #모양을 3행 5열로 만든다 
print(x)

In [ ]:
import numpy as np
a = [1,2,3,4,5]
b = np.array(a)
c = np.array([1,3,5,])

print(a)
print(b) #쉼표 없음
print(c) #쉼표 없음 

b #쉼표 있음 



In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = a
c = a.copy()
b[0] = 99


print(a)
print(b)
print(c) 

In [ ]:
a = [1,2,3,4,5]
b = np.array(a)
c = np.array([1,3,5])

print(b[2])
print(c[-1])
print(c[0:2]) #[0]부터 [2]미만! 이라 [2]는 미포함 


In [ ]:
print(a*2)

print(b*2) #np는 각각의 요소에 2가 곱해짐

print(c+3) #얘도 np니까 각각의 요소에 +3이 일괄적으로 됨 

In [ ]:
a = np.array([1,2.3,3],dtype = int)
b = np.array([1.1,2.2,3.3])
c = np.array([1.1,2,3])

print(a)
print(a.dtype)
print(b.dtype)
print(c)


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[1,2]]])

print(a[2])
print(a[2][0])
print(b[0])
print(b[0][0])
print(b[0][0][0])
print(b.shape)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(a[0])
print(a[0][2])
print(a.shape)

In [ ]:
import sys
import cv2

print('Hello OpenCV',cv2.__version__) #opencv의 version출력

image = cv2.imread('./image/dog.jpg') 
if image is None: #image값이 없으면 즉 해당 폴더에 image file이 없다면
    print('Image load failed!')
    sys.exit() #나가버려 

print(type(image))
print(image.dtype)
print(image)


In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(len(a)) #행의 개수
print(len(a[0])) #열의 개수
print(a.ndim) #배열의 차원
print(a.shape) #배열의 크기

[[1 2 3]
 [4 5 6]]
2
3
2
(2, 3)


In [11]:
#배열의 크기 변경
import numpy as np
na = np.arange(12)
print(na)

nb = na.reshape(3,4)
print(nb)

nc = na.reshape(3,-1)
print(nc)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
import numpy as np

nc = nb.flatten() #rave 함수도 있음 
print(nc)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
a = np.array([[0,1,2,3],[4,5,6,7]])

print(a[0,0])
print(a[:,2])
print(a[1,1:])

0
[2 6]
[5 6 7]


In [14]:
import numpy as np
na = np.zeros(5, dtype="U4")
print(na)

['' '' '' '' '']
